### ISSUE TITLE
make it possible to provision data disks

### ISSUE THREAD

**Issue by displague** [linode/docker-machine-driver-linode#12]
https://kubernetes.slack.com/archives/CD4B15LUR/p1550249658034200

In use cases like running Rook in Rancher deployed clusters, it would be helpful if additional disks could be provisioned via the Docker machine driver.

This option could look like:

* `--linode-data=100` (gb)
* `--linode-sdb-size=100` 
  (this could allow for each disk to be specified, how does it affect the swap drive? pushed into the next available slot?)
* `--linode-sdb-format=raw` 
* `--linode-disks=20,30,40`
  (how does this affect the swap param)

Similar to https://github.com/linode/terraform-linode-k8s/pull/30

**Comment by lots0logs** [comment]
@displague Any update on this? We need to be able to define both disk config and boot config from terraform using rancher. It's not possible currently without creating the nodes yourself using linode provider and then importing them into rancher.

![bump](https://user-images.githubusercontent.com/4675662/78603669-23036b00-781e-11ea-8f4a-2e58635d166e.gif)

**Comment by jriddle-linode** [comment]
Now that Docker Machine has been deprecated we suggest using Rancher with LKE. For now we're going to close this issue.
