### ISSUE TITLE
Unable to verify the Docker daemon is listening

### ISSUE THREAD

**Issue by patricktslee** [linode/docker-machine-driver-linode#17]
Hi All,

I have a problem when I use docker-machine create -d linode --linode-token=$LINODE_TOKEN linode1.  It raised " **Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded** ".

I login the Linode node and check the systemctl status docker after it is completed the "installing docker".  The docker is running in the node but don't know why it finally raises the error "Unable to verify the Docker daemon is listening".

And my docker-machine ls show the **Unknown** on DOCKER and **Unable to query docker version: Cannot connect to the docker engine endpoint** on ERRORS.  I have to reboot the Linode node and my docker-machine can connect it without any issue.

Please see the below information.  Are you able to re-produce the error on your side?

### docker-machine create log

```
docker-machine create -d linode --linode-token=$LINODE_TOKEN linode1
Running pre-create checks...
(linode1) Generating a secure disposable linode-root-pass...
Creating machine...
(linode1) Creating Linode machine instance...
(linode1) Waiting for Machine Running...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
```

### docker-machine ls log

```
docker-machine ls                             
NAME      ACTIVE   DRIVER   STATE     URL                       SWARM   DOCKER    ERRORS
linode1   -        linode   Running   tcp://45.79.136.43:2376           Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint

```

### After reboot the Linode Node linode1, docker-machine ls log

```
docker-machine ls
NAME      ACTIVE   DRIVER   STATE     URL                       SWARM   DOCKER     ERRORS
linode1   -        linode   Running   tcp://45.79.136.43:2376           v20.10.1   

```

### My docker-machine version

```
docker-machine version
docker-machine version 0.16.0, build 702c267f

```

Thanks

Patrick Lee

**Comment by mwolf1989** [comment]
I think this is nothing special for linode docker-machine driver but related to the docker version 20. I face the same problems using other clouds. 

See here: https://github.com/docker/machine/issues/4858

If you have no need for the docker 20 version you can pass a older using 

e.g. 

`--engine-install-url https://releases.rancher.com/install-docker/19.03.sh`

**Comment by LBGarber** [comment]
Hey there!

I'm closing this issue due to the `docker-machine` deprecation and the workaround posted above. Unfortunately, the resolution for this issue appears to rely on a fix upstream.

Let us know if you have any other issues!
