### ISSUE TITLE
Broken by changes in linode/linodego

### ISSUE THREAD

**Issue by al45tair** [linode/docker-machine-driver-linode#2]
The commit 
https://github.com/linode/linodego/commit/aaff5e823f8a3f1a1d3aa753b959a16ed68037f1 as described [here](https://github.com/linode/linodego/issues/40) broke `docker-machine-driver-linode`, which wasn't updated to match the new function signatures.

**Comment by al45tair** [comment]
Pull request https://github.com/linode/docker-machine-driver-linode/pull/1 should fix this problem.

**Comment by displague** [comment]
We should pin (update `Gopkg.toml`, `dep ensure`) to https://github.com/linode/linodego/releases/tag/v0.5.1 (or whatever is latest at time of PR).

**Comment by displague** [comment]
Merged - Thanks!
