### ISSUE TITLE
Run stackscript on machine creation

### ISSUE THREAD

**Issue by al45tair** [linode/docker-machine-driver-linode#3]
A default created Linode isn't 100% secure, particularly if the root password chosen wasn't terribly strong. Personally I prefer to do the following with every new Linode I create:

1. Create a non-root user in the group "admin" (so they can sudo to root if need be).
2. Disable root login over SSH.
3. Install SSH public keys and disable password authentication over SSH.
4. Move the SSH daemon to a port other than 22 (to avoid Chinese servers hammering at the door).

I might also want to perform some other administrative tasks, such as

- Enabling and configuring a firewall.
- Configuring the mail system to forward via a mail gateway.
- Installing logwatch to monitor the instance.

At the moment, `docker-machine-driver-linode` has no way to automate these things — but it could easily run a user-selectable Stackscript on node creation, which would provide users with a way to do these kinds of basic administrative tasks automatically.

**Comment by displague** [comment]
Your preferences (1-3) sound similar to mine: https://www.linode.com/stackscripts/view/10079

**Comment by displague** [comment]
You may also be interested in https://github.com/linode/docker-machine-driver-linode/issues/5

**Comment by displague** [comment]
I think linode/linodego#51 may create some problems for non-string parameters.  

Closing this out -- Thanks for the help @al45tair !

You may also be interested in:
- https://github.com/linode/docker-volume-linode
- https://github.com/displague/ui-driver-linode

If you are in the Gopher's Slack, join #linodego
https://invite.slack.golangbridge.org/
https://gophers.slack.com/messages/CAG93EB2S
